# Generated by Django 3.1.1 on 2020-09-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=40)),
                ('contactNumber', models.CharField(max_length=13)),
                ('alternateContactNumber', models.CharField(max_length=13)),
            ],
        ),
    ]
