# Generated by Django 3.1.1 on 2020-09-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='fullName',
            new_name='full_Name',
        ),
    ]
