# Generated by Django 3.1.1 on 2020-09-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200921_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='alternateContactNumber',
            new_name='alternate_Contact_Number',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='contactNumber',
            new_name='contact_Number',
        ),
    ]
