# Generated by Django 3.1.1 on 2020-09-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200921_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_visitors', to='main_app.userprofile'),
        ),
    ]
