# Generated by Django 3.1.1 on 2020-09-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_visitor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_Visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
