# Generated by Django 3.1 on 2020-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
