# Generated by Django 3.1.1 on 2020-09-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200922_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='alternate_Contact_Number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_Date', models.DateTimeField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.visitor')),
            ],
        ),
    ]
