# Generated by Django 3.1.1 on 2020-09-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200923_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main_app.visitor'),
        ),
    ]
