# Generated by Django 3.1.1 on 2020-09-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200923_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='first_Visit',
            new_name='date_Registered',
        ),
    ]
