# Generated by Django 3.1.1 on 2020-09-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200923_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_visits', to='main_app.userprofile'),
        ),
        migrations.AddField(
            model_name='visitdetails',
            name='visit_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
