# Generated by Django 3.1.1 on 2020-09-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200923_1837'),
        ('main_app', '0012_auto_20200923_1130'),
    ]

    operations = [
    ]
