# Generated by Django 3.1 on 2020-09-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200923_1130'),
        ('main_app', '0011_auto_20200923_1837'),
    ]

    operations = [
    ]
