# Generated by Django 3.1 on 2020-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20200924_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
