# Generated by Django 3.1.1 on 2020-09-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20200923_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, default='/default_visitor.png', null=True, upload_to='visitors_photos/'),
        ),
    ]
