# Generated by Django 3.1.1 on 2020-09-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_visitor_photo'),
        ('main_app', '0014_visitor_last_visit'),
    ]

    operations = [
    ]
